// Generated by cargo run -p interfaces --example export_admin_contract. Do not edit.

export type AccessSettings = { registration_enabled: boolean, guest_comments_enabled: boolean, version: number, };

export type AccountStatus = "active" | "disabled";

export type AdminUser = { id: string, username: string, email: string | null, display_name: string | null, status: string, version: number, deleted: boolean, can_login: boolean, is_last_loginable_admin: boolean, password_enabled: boolean, external_identities: number, roles: Array<string>, };

export type AuditField = { key: string, value: string, };

export type AuditPage = { items: Array<AuditRecord>, next_cursor: string | null, };

export type AuditRecord = { id: string, created_at: string, actor_id: string | null, actor_display: string | null, ip_address: string | null, action: string, target_type: string, target_id: string, summary: Array<AuditField>, };

export type CategorySummary = { id: string, slug: string, name: string, parent_id: string | null, description: string | null, version: number,
/**
 * 直接归属的公开文章计数。
 */
pub_post_count: number, };

export type ChangePasswordInput = {
/**
 * 已启用密码登录时必填：用于重新认证（docs §5）。
 */
current_password?: string | null, new_password: string, };

export type ChangeStatusInput = { status: AccountStatus, expected_version: number, };

export type CommentItem = { id: string, post_id: string, post_slug: string, post_title: string, parent_id: string | null, root_id: string | null, parent_nickname: string | null, author_email: string | null, ip_address: string | null, content_html: string, nickname: string, body: string, is_author: boolean, status: string, moderation_reason: string | null, version: number, created_at: string, };

export type CommentModerationMode = "all" | "guests" | "first_comment" | "none";

export type CommentPage = { items: Array<CommentItem>, total: number, enabled: boolean, };

export type CommentPolicy = { enabled: boolean, moderation?: CommentModerationMode | null, version: number, };

export type CommentPreviewInput = { body: string, };

export type CommentSubmissionResult = { message: string, status: string, };

export type ContentPage<T> = { items: Array<T>, total: number, page: number, per_page: number, };

export type ContentPreviewInput = { content: string, };

export type ContentPreviewResult = { content_html: string,
/**
 * Generated by trusted plugin resource hooks, never by Markdown authors.
 */
head_html: string, };

export type CreateCategoryInput = { name: string, slug: string,
/**
 * 父分类 slug；缺省为根分类。
 */
parent?: string | null, description?: string | null, };

export type CreatePageInput = { slug?: string | null, title: string, content: string, visibility?: string | null, };

export type CreatePostInput = { slug?: string | null, title: string, excerpt?: string | null, content: string, visibility?: string | null,
/**
 * 初始标签 id 集合（去重与存在性由用例处理）。
 */
tag_ids?: Array<string>,
/**
 * 初始分类 id（存在性由用例校验）。
 */
category_id?: string | null,
/**
 * 初始系列与序号。
 */
series?: Array<SeriesPlacement>,
/**
 * 初始封面媒体资产 id（缺省 = 无封面）。
 */
cover_media_id?: string | null, };

export type CreateSeriesInput = { name: string, slug: string, description?: string | null, };

export type CreateTagInput = { name: string, slug: string, };

export type CreateUserInput = { username: string, email?: string | null, display_name?: string | null, };

export type CreatedUser = { id: string, username: string, display_name: string | null, created_at: string, };

export type DeletePageInput = { expected_version: number, };

export type EditPageInput = { new_slug?: string | null, title?: string | null, content?: string | null, visibility?: string | null, expected_version?: number | null, };

export type EditPostInput = { new_slug?: string | null, title?: string | null, excerpt?: string | null, content?: string | null, visibility?: string | null,
/**
 * Some 表示整体替换标签集合（[] = 清空）；缺省不触碰。
 */
tag_ids?: Array<string> | null,
/**
 * 三态：缺省不修改；null 清空分类；id 设置分类。
 */
category_id?: string | null,
/**
 * 缺省保留，数组整体替换；空数组清空。
 */
series?: Array<SeriesPlacement> | null,
/**
 * 封面三态：缺省不修改；null 移除封面；id 设置封面。
 */
cover_media_id?: string | null, expected_version?: number | null, };

export type HtmlRebuildCounts = { posts: number, pages: number, comments: number, };

export type HtmlRebuildFailure = { kind: HtmlRebuildKind | null, id: string | null, message: string, };

export type HtmlRebuildJob = { id: string, status: HtmlRebuildJobStatus, report: HtmlRebuildReport, };

export type HtmlRebuildJobStatus = "running" | "completed" | "failed" | "interrupted";

export type HtmlRebuildKind = "post" | "page" | "comment";

export type HtmlRebuildReport = { rebuilt: HtmlRebuildCounts, skipped: HtmlRebuildCounts, pending: HtmlRebuildCounts | null, batches: number, has_more: boolean, dry_run: boolean, failure: HtmlRebuildFailure | null, };

export type HtmlRebuildView = { pending: HtmlRebuildCounts | null, job: HtmlRebuildJob | null, available: boolean, };

export type Me = { time_zone: string, permissions: Array<string>, csrf_token: string, channel: SessionChannel, user_id: string, username: string, display_name: string | null, bio: string | null, version: number, avatar_media_id: string | null, avatar_url: string | null, };

export type MediaAsset = { id: string, original_name: string, mime: string, byte_size: number, width: number, height: number, deleted_at: string | null, version: number, created_at: string, owner_id: string | null, owner_display: string, url: string,
/**
 * 已知引用数；软删除保留引用。
 */
reference_count: number, };

export type MediaPage = { items: Array<MediaAsset>, total: number, page: number, per_page: number, };

export type MediaReference = { kind: string, content_id: string, slug: string, title: string, status: string, visibility: string, deleted: boolean, public: boolean, };

export type MediaUsageView = { media: MediaAsset,
/**
 * 调用者有权查看的使用位置（按 Post own/any 与 Page 站点权限过滤）。
 */
references: Array<MediaReference>,
/**
 * 存在但调用者无权查看的引用数：计数是全局的，展示必须过滤，
 * 因此把差额如实返回，界面才能解释「为什么列出的比统计的少」。
 */
hidden_references: number, };

export type MediaVersionInput = { expected_version: number, };

export type MessageResult = { message: string, };

export type ModerateCommentInput = { version: number, status: string, };

export type NavigationItem = { label: string, page_slug: string, placement: NavigationPlacement, };

export type NavigationPlacement = "header" | "footer";

export type PageDetail = { content: string, id: string, slug: string, title: string, status: string, visibility: string, version: number, published_at: string | null, updated_at: string, };

export type PageSummary = { id: string, slug: string, title: string, status: string, visibility: string, version: number, published_at: string | null, updated_at: string, };

export type PasswordChangeResult = { user_id: string, csrf_token: string, };

export type PasswordLoginInput = { username: string, password: string, next?: string | null, };

export type PasswordLoginResult = { user_id: string, next: string, };

export type PluginConfigField = { key: string, label: string, description: string, default: PluginConfigValue, };

export type PluginConfigValue = boolean | number | string;

export type PluginHook = "content" | "page_head";

export type PluginView = { id: string, name: string, description: string, version: string, hooks: Array<PluginHook>, config_fields: Array<PluginConfigField>, available: boolean, enabled: boolean, config: { [key in string]: PluginConfigValue }, };

export type PluginsView = { version: number, plugins: Array<PluginView>, };

export type PostDetail = { excerpt: string | null, content: string, id: string, slug: string, title: string, status: string, visibility: string, version: number, published_at: string | null, updated_at: string, author_id: string,
/**
 * 当前关联标签 id（按 id 升序）；名称由前端结合标签目录解析。
 */
tag_ids: Array<string>,
/**
 * 所属分类 id（None = 未分类）。
 */
category_id: string | null, series: Array<SeriesPlacement>,
/**
 * 封面媒体资产 id（None = 无封面）。
 */
cover_media_id: string | null,
/**
 * 封面站内地址（`/media/{id}`）；None = 无封面。
 */
cover_url: string | null, };

export type PostMetadata = { id: string, slug: string, title: string, status: string, visibility: string, version: number, published_at: string | null, updated_at: string, author_id: string,
/**
 * 当前关联标签 id（按 id 升序）；名称由前端结合标签目录解析。
 */
tag_ids: Array<string>,
/**
 * 所属分类 id（None = 未分类）。
 */
category_id: string | null, series: Array<SeriesPlacement>,
/**
 * 封面媒体资产 id（None = 无封面）。
 */
cover_media_id: string | null,
/**
 * 封面站内地址（`/media/{id}`）；None = 无封面。
 */
cover_url: string | null, };

export type PostSummary = { author_username: string, id: string, slug: string, title: string, status: string, visibility: string, version: number, published_at: string | null, updated_at: string, author_id: string, };

export type PreviewResult = { content_html: string, };

export type Profile = { user_id: string, username: string, display_name: string | null, bio: string | null, version: number, avatar_media_id: string | null, avatar_url: string | null, };

export type ProviderSummary = { id: string, name: string, kind: string, };

export type RegistrationInput = { username: string, display_name?: string | null, email: string, password: string, };

export type RegistrationStatus = { enabled: boolean, };

export type RenameTagInput = { name: string, expected_version?: number | null, };

export type ReorderSeriesInput = {
/**
 * 系列内全部文章 id 按目标顺序（完整排列）。
 */
ordered_post_ids: Array<string>, expected_series_version?: number | null, };

export type ReorderSeriesResult = { series_version: number, ordered_post_ids: Array<string>, };

export type RetentionSettings = { comment_ip_days: number, comment_version: number, audit_days: number, audit_version: number, };

export type RoleSummary = { slug: string, name: string, description: string | null, builtin: boolean, permission_count: number, };

export type SavePluginInput = { enabled: boolean, config: { [key in string]: PluginConfigValue }, expected_version: number, };

export type SaveSiteSettingsInput = { home_page_size?: number | null, navigation?: Array<NavigationItem> | null, time_zone?: string | null, title: string, description: string,
/**
 * 站点 logo（PUT 是整组替换：缺省/null = 清除 logo）。
 */
logo_media_id?: string | null, expected_version?: number | null, };

export type SaveThemeSettingsInput = { slug: string, expected_version?: number | null, };

export type ScheduleInput = { published_at: string, expected_version?: number | null, };

export type SeriesMemberRow = { id: string, slug: string, title: string, status: string, deleted: boolean, visibility: string, author_id: string, position: number, };

export type SeriesPlacement = { series_id: string, position: number, };

export type SeriesSummary = { id: string, slug: string, name: string, description: string | null,
/**
 * 封面媒体资产 id（None = 无封面）。
 */
cover_media_id: string | null,
/**
 * 封面站内地址（`/media/{id}`）；None = 无封面。
 */
cover_url: string | null, version: number,
/**
 * 成员总数（含草稿/私密/回收站）；无 post.read_any 时为 null。
 */
post_count: number | null, pub_post_count: number, };

export type SessionChannel = "session";

export type SetAvatarInput = { expected_version: number,
/**
 * 缺省或 null = 清除头像；id = 设置头像（PUT 是整值替换，非三态）。
 */
avatar_media_id?: string | null, };

export type SiteSettings = { home_page_size: number, navigation: Array<NavigationItem>, time_zone: string, time_zones: Array<string>, title: string, description: string,
/**
 * 站点 logo 的媒体资产 id（None = 无 logo）。
 */
logo_media_id: string | null,
/**
 * 站点 logo 的站内地址（None = 无 logo）。
 */
logo_url: string | null,
/**
 * "database"（settings.site 行）或 "fallback"（内置默认值，version=0）。
 */
source: string, version: number, };

export type SiteSettingsSource = "database" | "fallback";

export type SubmitCommentBody = { nickname?: string | null, body: string, parent_id?: string | null, email?: string | null, };

export type TagSummary = { id: string, slug: string, name: string, version: number,
/**
 * 公开文章计数（与公开标签页同口径）。
 */
public_post_count: number, };

export type TaskKind = "html_rebuild" | "retention" | "publish_due";

export type TaskPublicationResult = { published: number, batches: number, has_more: boolean, };

export type TaskReport = { html: HtmlRebuildReport | null, retention: TaskRetentionResult | null, publication: TaskPublicationResult | null, error: string | null, };

export type TaskRetentionResult = { comment_ips: number, audit_logs: number, batches: number, has_more: boolean, dry_run: boolean, };

export type TaskRun = { id: string, kind: TaskKind, status: TaskStatus, trigger: TaskTrigger, run_at: string, created_at: string, started_at: string | null, finished_at: string | null, retry_of: string | null, report: TaskReport, can_retry: boolean, can_cancel: boolean, };

export type TaskRunPage = { items: Array<TaskRun>, next_cursor: string | null, };

export type TaskSchedule = { kind: TaskKind, enabled: boolean, interval_seconds: number, next_run_at: string | null, version: number, };

export type TaskScheduleBody = { enabled: boolean, interval_seconds: number, next_run_at: string | null, version: number, };

export type TaskStartBody = { kind: TaskKind, run_at: string | null, };

export type TaskStatus = "queued" | "running" | "completed" | "failed" | "interrupted" | "cancelled";

export type TaskTrigger = "manual" | "once" | "periodic" | "retry";

export type TaskView = { available: boolean, retention_available: boolean, pending_html: HtmlRebuildCounts | null, schedules: Array<TaskSchedule>, latest: Array<TaskRun>, runs: TaskRunPage, };

export type ThemeOption = { slug: string, name: string, release: string, };

export type ThemePackageReport = { slug: string, name: string, release: string, template_count: number, asset_count: number, };

export type ThemeSettings = { slug: string, effective_slug: string, fallback_slug: string, source: SiteSettingsSource, version: number, available: Array<ThemeOption>, };

export type UninstallThemeInput = { expected_version: number, expected_release: string, };

export type UpdateCategoryInput = { name: string, description?: string | null,
/**
 * 三态：缺省保持现状；null 移到根；slug 移到指定父。
 */
parent?: string | null, expected_version?: number | null, };

export type UpdateProfileInput = { display_name?: string | null, bio?: string | null, expected_version: number, };

export type UpdateSeriesInput = { name: string, description?: string | null,
/**
 * 封面三态：缺省不修改；null 移除封面；id 设置封面。
 */
cover_media_id?: string | null, expected_version?: number | null, };

export type UserStatusResult = { id: string, status: string, version: number, };

export type VersionInput = { expected_version?: number | null, };
