//! TypeScript contract generated from the DTOs actually used by HTTP handlers.
mod audit;
mod comments;
mod common;
mod html_rebuild;
mod identity;
mod settings;
mod tasks;
pub use audit::*;
pub use comments::*;
pub use common::*;
pub use html_rebuild::*;
pub use identity::*;
pub use settings::*;
pub use tasks::*;

pub(crate) fn declare<T: ts_rs::TS>(out: &mut Vec<String>) {
    // serde_json sends integers as JSON numbers; UUIDs are strings.
    out.push(format!(
        "export {}",
        T::decl(&ts_rs::Config::new().with_large_int("number"))
    ));
}

pub fn typescript() -> String {
    let mut out = Vec::new();
    declare::<ContentPage<String>>(&mut out);
    declare::<SeriesPlacement>(&mut out);
    declare::<PreviewResult>(&mut out);
    declare::<MessageResult>(&mut out);
    declare::<Profile>(&mut out);
    declare::<AdminUser>(&mut out);
    declare::<CreatedUser>(&mut out);
    declare::<UserStatusResult>(&mut out);
    declare::<Me>(&mut out);
    declare::<SessionChannel>(&mut out);
    declare::<PasswordLoginResult>(&mut out);
    declare::<PasswordChangeResult>(&mut out);
    declare::<RoleSummary>(&mut out);
    declare::<ReorderSeriesResult>(&mut out);
    declare::<ProviderSummary>(&mut out);
    declare::<ThemeOption>(&mut out);
    declare::<SiteSettingsSource>(&mut out);
    declare::<ThemeSettings>(&mut out);
    declare::<RetentionSettings>(&mut out);
    declare::<AuditField>(&mut out);
    declare::<AuditRecord>(&mut out);
    declare::<AuditPage>(&mut out);
    declare::<HtmlRebuildCounts>(&mut out);
    declare::<HtmlRebuildKind>(&mut out);
    declare::<HtmlRebuildFailure>(&mut out);
    declare::<HtmlRebuildReport>(&mut out);
    declare::<HtmlRebuildJobStatus>(&mut out);
    declare::<HtmlRebuildJob>(&mut out);
    declare::<HtmlRebuildView>(&mut out);
    declare::<TaskKind>(&mut out);
    declare::<TaskStatus>(&mut out);
    declare::<TaskTrigger>(&mut out);
    declare::<TaskRetentionResult>(&mut out);
    declare::<TaskPublicationResult>(&mut out);
    declare::<TaskReport>(&mut out);
    declare::<TaskRun>(&mut out);
    declare::<TaskSchedule>(&mut out);
    declare::<TaskRunPage>(&mut out);
    declare::<TaskView>(&mut out);
    declare::<TaskStartBody>(&mut out);
    declare::<TaskScheduleBody>(&mut out);
    declare::<CommentPolicy>(&mut out);
    declare::<CommentModerationMode>(&mut out);
    declare::<CommentSubmissionResult>(&mut out);
    declare::<SubmitCommentBody>(&mut out);
    crate::http_admin::export_contract(&mut out);
    crate::http_media::export_contract(&mut out);
    crate::http_comments::export_contract(&mut out);
    crate::http_auth::export_contract(&mut out);
    crate::http_identity::export_contract(&mut out);
    crate::http_content_preview::export_contract(&mut out);
    crate::http_registration::export_contract(&mut out);
    crate::http_plugins::export_contract(&mut out);
    crate::http_themes::export_contract(&mut out);
    out.sort();
    format!(
        "// Generated by cargo run -p interfaces --example export_admin_contract. Do not edit.\n\n{}\n",
        out.join("\n\n")
            .lines()
            .map(str::trim_end)
            .collect::<Vec<_>>()
            .join("\n")
    )
}
