[package]
name = "interfaces"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { path = "../application" }
axum.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
prometheus = { version = "0.14", default-features = false }
tower-http = { version = "0.6", features = ["fs"] }
mime_guess = "2"
rpassword.workspace = true
ts-rs = { version = "12", features = ["uuid-impl"] }
