-- Generated by scripts/schema_contract.py --write; do not edit.
-- Run as the schema owner after `blog migrate`. Both LOGIN roles must already
-- exist and must not own schema objects or inherit a more privileged role.
-- psql "$DATABASE_URL" -v app_role=blog_app -v maintenance_role=blog_maintenance -f scripts/database-roles.sql
\set ON_ERROR_STOP on
BEGIN;
SELECT set_config('blog.app_role', :'app_role', true),
       set_config('blog.maintenance_role', :'maintenance_role', true);
DO $$
DECLARE name text; role_oid oid;
BEGIN
  IF current_setting('blog.app_role') = current_setting('blog.maintenance_role') THEN
    RAISE EXCEPTION 'Application and maintenance roles must be distinct';
  END IF;
  FOREACH name IN ARRAY ARRAY[current_setting('blog.app_role'),current_setting('blog.maintenance_role')] LOOP
    SELECT oid INTO role_oid FROM pg_roles WHERE rolname=name AND rolcanlogin
      AND NOT rolsuper AND NOT rolcreaterole AND NOT rolcreatedb AND NOT rolbypassrls;
    IF role_oid IS NULL THEN RAISE EXCEPTION 'Role % must be an unprivileged LOGIN role',name; END IF;
    IF EXISTS(SELECT 1 FROM pg_auth_members WHERE member=role_oid)
      OR EXISTS(SELECT 1 FROM pg_class WHERE relowner=role_oid)
      OR EXISTS(SELECT 1 FROM pg_namespace WHERE nspowner=role_oid)
      OR EXISTS(SELECT 1 FROM pg_database WHERE datdba=role_oid) THEN
      RAISE EXCEPTION 'Role % must not own objects or have role memberships',name;
    END IF;
  END LOOP;
END $$;
-- Refuse an incomplete contract before changing any privileges.
DO $$
BEGIN
  IF (SELECT array_agg(table_name::text ORDER BY table_name)
      FROM information_schema.tables
      WHERE table_schema='public' AND table_type='BASE TABLE'
        AND table_name<>'_sqlx_migrations') IS DISTINCT FROM ARRAY['audit_logs','categories','comments','media','media_refs','oauth_accounts','pages','permissions','post_series','post_tags','posts','role_permissions','roles','series','sessions','settings','tags','task_runs','task_schedules','themes','user_roles','users']::text[] THEN
    RAISE EXCEPTION 'Database tables differ from schema.json; use the matching release';
  END IF;
END $$;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM :"app_role", :"maintenance_role";
-- Table-level REVOKE does not remove old column-level grants. Reset these too
-- so a later policy can remove a formerly allowed column without leaving access.
DO $$
DECLARE relation record; role_name text;
BEGIN
  FOR relation IN
    SELECT table_name, string_agg(format('%I',column_name),',' ORDER BY ordinal_position) AS columns
    FROM information_schema.columns WHERE table_schema='public' GROUP BY table_name
  LOOP
    FOREACH role_name IN ARRAY ARRAY[current_setting('blog.app_role'),current_setting('blog.maintenance_role')] LOOP
      EXECUTE format('REVOKE SELECT (%s), INSERT (%s), UPDATE (%s), REFERENCES (%s) ON TABLE public.%I FROM %I',
        relation.columns,relation.columns,relation.columns,relation.columns,relation.table_name,role_name);
    END LOOP;
  END LOOP;
END $$;
REVOKE ALL ON SCHEMA public FROM :"app_role", :"maintenance_role";
GRANT USAGE ON SCHEMA public TO :"app_role", :"maintenance_role";
GRANT SELECT ON public._sqlx_migrations TO :"app_role";
GRANT SELECT,INSERT ON public."audit_logs" TO :"app_role";
GRANT SELECT(id,created_at),INSERT,DELETE ON public."audit_logs" TO :"maintenance_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."categories" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."comments" TO :"app_role";
GRANT SELECT(id,created_at,ip_address),UPDATE(ip_address) ON public."comments" TO :"maintenance_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."media" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."media_refs" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."oauth_accounts" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."pages" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."permissions" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."post_series" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."post_tags" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."posts" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."role_permissions" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."roles" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."series" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."sessions" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."settings" TO :"app_role";
GRANT SELECT ON public."settings" TO :"maintenance_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."tags" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."task_runs" TO :"app_role";
GRANT SELECT,UPDATE ON public."task_runs" TO :"maintenance_role";
GRANT SELECT,INSERT,UPDATE ON public."task_schedules" TO :"app_role";
GRANT SELECT ON public."task_schedules" TO :"maintenance_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."themes" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."user_roles" TO :"app_role";
GRANT SELECT,INSERT,UPDATE,DELETE ON public."users" TO :"app_role";

-- Detect PUBLIC/inherited grants instead of silently claiming an append-only role.
DO $$
DECLARE app text := current_setting('blog.app_role'); maint text := current_setting('blog.maintenance_role');
BEGIN
  IF has_table_privilege(app,'audit_logs','UPDATE,DELETE,TRUNCATE')
    OR has_any_column_privilege(app,'audit_logs','UPDATE')
    OR has_schema_privilege(app,'public','CREATE')
    OR has_table_privilege(maint,'audit_logs','UPDATE,TRUNCATE')
    OR has_any_column_privilege(maint,'audit_logs','UPDATE')
    OR has_column_privilege(maint,'comments','content','UPDATE')
    OR has_schema_privilege(maint,'public','CREATE') THEN
    RAISE EXCEPTION 'Unexpected privileges remain; inspect PUBLIC and column grants';
  END IF;
END $$;
COMMIT;
