[package]
name = "server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "blog"
path = "src/main.rs"

[dependencies]
application = { path = "../application" }
infrastructure = { path = "../infrastructure" }
interfaces = { path = "../interfaces" }
tokio.workspace = true
axum.workspace = true
sqlx.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

serde_json.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
async-trait.workspace = true
uuid.workspace = true
domain = { path = "../domain" }
